apiVersion: v1
kind: PersistentVolume
metadata:
  name: foodiespv
  labels:
    app: foodiespv
spec:
  storageClassName: foodiesstorageclass
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteMultiple
  hostPath:
    path: "/u01/data"
