apiVersion: v1
kind: Pod
metadata:
  name: foodiespod
  labels:
    name: foodies
spec:
  containers:
  - name: foodies
    image: hemanadhareddy/foodies:1.0
    ports:
    - name: tomcatport
      containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /data/fetch
        port: 8080
      initialDelaySeconds: 60
      timeoutSeconds: 10
    resources:
      requests:
        cpu: "500m"
        memory: "512Mi"
      limits:
        cpu: "1000m"
        memory: "1000Mi"
      # env:
    # - name: username
    #   valueFrom:
    #     configMapKeyRef:
    #       name: foodiesconfigmap
    #       key: username
    # - name: password
    #   valueFrom:
    #     configMapKeyRef:
    #       name: foodiesmyappconfigmap
    #       key: password
    volumeMounts:
    - name: foodiesvolume
      mountPath: "/u01/data"
volumes:
- name: foodiesvolume
  persistentVolumeClaim:
    claimName: foodiespvc
