apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foodiespvc
  labels:
    app: foodiespvc
spec:
  storageClassName: foodiesstorageclass
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
